COMPILE_DEPS = [
    '//lib:CORE_DEPS',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)

onos_app (
    title = 'Intent Reactive Forwarding App',
    category = 'Traffic Steering',
    url = 'http://onosproject.org',
    description = 'Intent reactive forwarding application using the intent subsystem.',
)
